# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-04 01:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Railserve', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='latitude',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),

        ),
        migrations.AddField(
            model_name='position',
            name='longitude',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),

        ),
    ]
