# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-04 01:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Railserve', '0002_auto_20170404_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='latitude',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='position',
            name='longitude',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
    ]
