# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-04 01:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Railserve', '0003_auto_20170404_0104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='position',
            name='longitude',
        ),
    ]
