# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-13 18:49
from __future__ import unicode_literals

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('Railserve', '0005_auto_20170404_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='date',
            field=models.DateField(auto_now=True,
                                   default=datetime.datetime(2017, 4, 13, 18, 49, 31, 443363, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
