# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-13 18:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('Railserve', '0006_device_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='device',
            unique_together=set([('position', 'id')]),
        ),
    ]
