# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-14 02:53
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Railserve', '0008_auto_20170414_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='device',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False,
                                    to='Railserve.Position'),
        ),
    ]
