# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-14 03:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Railserve', '0010_auto_20170414_0254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='date',
            field=models.DateTimeField(auto_now=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='device',
            name='id',
            field=models.IntegerField(),
        ),
    ]
